### ISSUE TITLE
VSCode / non-Steam apps

### ISSUE THREAD

**Issue by ShalokShalom** [suppressio/vr-pico4-steam-linux#1]
Hi :)

Can I use other Linux apps, such as VSCode with this tutorial?

Or is this only for Steam games?

**Comment by suppressio** [comment]
Hi, 
you can use any "VR" applications, such as games in the Steam library that are native or supported VR, or other VR applications that use Steam-VR as a launcher (such as Google Earth VR or BigScreen).

You can also use steam-vr to launch VR applications not available in the steam library by adding them manually... but I don't think that's what you're looking for.

What you are asking for, I think, is something like [xrdesktop](https://gitlab.freedesktop.org/xrdesktop/xrdesktop/-/blob/main/README.md) or [SimulaVR](https://github.com/SimulaVR/Simula)... but I haven't tried these software yet....
